DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_RED)
DEF PLAYERNAME1 EQUS "RED"
DEF PLAYERNAME2 EQUS "SACHA"
DEF PLAYERNAME3 EQUS "PAUL"

DEF RIVALNAME1 EQUS "BLUE"
DEF RIVALNAME2 EQUS "REGIS"
DEF RIVALNAME3 EQUS "JEAN"
ENDC

IF DEF(_BLUE)
DEF PLAYERNAME1 EQUS "BLUE"
DEF PLAYERNAME2 EQUS "REGIS"
DEF PLAYERNAME3 EQUS "JEAN"

DEF RIVALNAME1 EQUS "RED"
DEF RIVALNAME2 EQUS "SACHA"
DEF RIVALNAME3 EQUS "PAUL"
ENDC
